### PR TITLE
fixed link to findRecipe page

### PR DESCRIPTION
**Pull request by LouiseKMiller**
findAllIngredients routine in helpers file was changed to require an additional parameter identifying the view page.

### CODE REVIEW

**Comment by LouiseKMiller** [comment]
made some example style changes

**Comment by LouiseKMiller** [comment]
we were getting duplicate categories.  fixed this in getRecipes file

**Comment by LouiseKMiller** [comment]
made some more changes

**Comment by apexpatel11** [comment]
changed recipe page

**Comment by apexpatel11** [comment]
changes done

**Pull request merged**
